### ISSUE TITLE
创意：控制拖拽组件放大或缩小按刻度实现

### ISSUE THREAD

**Issue by carpONE** [xachary/konva-designer-sample#10]
1、控制移动时按刻度10或者20，符合背景刻度；
2、将放大或缩小时也是按刻度来控制

**Comment by carpONE** [comment]
像这个一样：https://vangleer.github.io/es-drager/#/grid

**Comment by xachary** [comment]
> 1、控制移动时按刻度10或者20，符合背景刻度； 2、将放大或缩小时也是按刻度来控制

@carpONE 出发点不一样，很多时候就是需要1~几个像素的移动，素材也不是网格的整数倍大小。不反对 fork 一个实现自己的想法，即使在这个库的基础上，应该也是可以调整过来的：1、素材要满足整数倍；2、修改磁贴的逻辑，强制整数倍的变化；

**Comment by xachary** [comment]
> 像这个一样：https://vangleer.github.io/es-drager/#/grid

@carpONE 大神自己写基础交互，不一样😊

**Comment by xachary** [comment]
> > 像这个一样：https://vangleer.github.io/es-drager/#/grid
> 
> @carpONE 大神自己写基础交互，不一样😊

从“磁贴”逻辑入手，改成必须整数倍与网格，应该可以实现。
