### ISSUE TITLE
我添加了一个文字,当我通过表单用户输入的文字字体大小修改时,Transformer不会更新宽度

### ISSUE THREAD

**Issue by bert1020** [xachary/konva-designer-sample#5]
高度会自动更新,
![image](https://github.com/xachary/konva-designer-sample/assets/46582197/329512bd-43fd-4a98-9045-1818433073d4)
类似于这样子

**Comment by xachary** [comment]
示例里面暂时没有含文字的处理哦，可以在官方提个 issue 问问，嘿嘿
@bert1020
