### ISSUE TITLE
group角度修改的问题

### ISSUE THREAD

**Issue by bert1020** [xachary/konva-designer-sample#6]
大佬,请教一下,我现在用表单修改选中元素的角度,如果修改group的角度,刷新图层没有更新.如果修改shape的角度,图层有更新,但保存之后重新导入的时候则会shape 和group 都会旋转一次 ,导致本来旋转25度 实际旋转了50度.

还有问一下为啥每个shape都要用一个group包裹一下?
`const rotationChange =(value:number) =>{
    let shape = render.stage.find('#' + activeEl.value.id)[0];
    //activeGroup.value.rotation=value;
     (shape.parent as Konva.Group).rotation(value);
     shape.rotation(value);
    // let group = render.stage.find('#' + activeGroup.value.id)[0];
    // group.rotation(value);
    // group.draw();
    render.layer.draw();
}`

**Comment by bert1020** [comment]
`const rotationChange =(value:number) =>{
    let shape = render.stage.find('#' + activeEl.value.id)[0];
    //activeGroup.value.rotation=value;
     (shape.parent as Konva.Group).rotation(value);
     shape.rotation(value);
    // let group = render.stage.find('#' + activeGroup.value.id)[0];
    // group.rotation(value);
    // group.draw();
    render.layer.draw();
}`

**Comment by bert1020** [comment]
也不是没有效果,是需要拖动一下 画布上才会更新

**Comment by bert1020** [comment]
(shape.parent as Konva.Group).transformsEnabled('none');
    (shape.parent as Konva.Group).transformsEnabled('all');
目前用这个方法,先禁止变换,再启用变换是可以了.不知道您这边是否有更好的方法

**Comment by xachary** [comment]
> 大佬,请教一下,我现在用表单修改选中元素的角度,如果修改group的角度,刷新图层没有更新.如果修改shape的角度,图层有更新,但保存之后重新导入的时候则会shape 和group 都会旋转一次 ,导致本来旋转25度 实际旋转了50度.
> 
> 还有问一下为啥每个shape都要用一个group包裹一下? `const rotationChange =(value:number) =>{ let shape = render.stage.find('#' + activeEl.value.id)[0]; //activeGroup.value.rotation=value; (shape.parent as Konva.Group).rotation(value); shape.rotation(value); // let group = render.stage.find('#' + activeGroup.value.id)[0]; // group.rotation(value); // group.draw(); render.layer.draw(); }`

我想法是 group 作为一切移动、变换的入口，而且一个元素不止图片本身，还有后面的连接点等等附属图形。

**Comment by xachary** [comment]
> 也不是没有效果,是需要拖动一下 画布上才会更新

外部改动了图形属性，需要重新 draw 一下，一层层的 draw，例如 Bg、Ruler、图形、预览等等

**Comment by xachary** [comment]
> group的角度,刷新图层没有更新

一切操作赋予 group，内部应该不变
