### ISSUE TITLE
多个图形对齐时，如果有图形先进行了旋转后，对齐会有问题

### ISSUE THREAD

**Issue by yyyyh** [xachary/konva-designer-sample#7]
![image](https://github.com/xachary/konva-designer-sample/assets/17631236/612ac6d3-b66d-4396-8d1c-ced63913e07a)

**Comment by xachary** [comment]
@yyyyh 是个问题，你觉得，旋转之后，对齐点应该参考它的哪一些？依旧是原来的“上下左右中”，还是旋转之后的？
