### ISSUE TITLE
内存泄露

### ISSUE THREAD

**Issue by bert1020** [xachary/konva-designer-sample#8]
我拿你的示例也测试了,有内存泄露

复现方式:
1.拖拽十几二十个图形上去
2.拖住一个一直移动,来回转圈,一会内存就上到2G多了

**Comment by xachary** [comment]
@bert1020 发现是哪里导致泄露了么？欢迎Pull requests！

**Comment by xachary** [comment]
@bert1020 优化了 68b0f1fcb5a30c63571c61d1271049512bb1793a
试试看

**Comment by bert1020** [comment]
src/Render/tools/ImportExportTool.ts  还有这个里面的getView方法  里面会clone一个 ,保存完也要销毁,不然一直保存一直克隆  我也是刚刚找到

**Comment by bert1020** [comment]
还是有地方会泄露

**Comment by xachary** [comment]
@bert1020 我测试了，主要的泄露是 每一帧 的刷新，需要 destroy 旧 group 内容，基本就不会超过 100 Mb；另外，类似 ImportExportTool 确实还可以优化一下，凡事 clone 的地方，也优化了。0542ad7055ce3fefb6a1ea7a08dc212f6d64fd49

![image](https://github.com/xachary/konva-designer-sample/assets/16830398/e42f8c17-892f-46a2-9b91-60a7e3339735)

**Comment by bert1020** [comment]
大佬牛逼 暂时可以了
