### ISSUE TITLE
怎样比例尺左侧刻度数字纵向显示？

### ISSUE THREAD

**Issue by programlife555** [xachary/konva-designer-sample#9]
请教，类似 https://image.h5ds.com/ 这个，比例尺左侧刻度数字纵向显示怎样做？

**Comment by xachary** [comment]
> 请教，类似 https://image.h5ds.com/ 这个，比例尺左侧刻度数字纵向显示怎样做？

任何 Shape（包括 Text） 应该都可以设置 rotate 旋转吧？逆时针旋转 90 度？

@programlife555

**Comment by programlife555** [comment]
![1721617525378](https://github.com/user-attachments/assets/e089e95c-7589-47dc-88fa-097f1aa711c9)
显示位置还有问题, 以下是实现代码，帮忙看看
``` ts
          /* 文字纵向显示(旋转270度) */
          while (this.getValue(text.width()) > this.getValue(cellSize) * 4.6) {
            fontSize -= 1
            text.fontSize(this.getValue(fontSize))
          }
          text.setAttrs({
            rotation: 270,
            x: text.height() / 2,
            offsetX: text.width() / 2,
            offsetY: text.height() / 2,
          });
```

**Comment by xachary** [comment]
> ![1721617525378](https://private-user-images.githubusercontent.com/1399963/350825136-e089e95c-7589-47dc-88fa-097f1aa711c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MTY2NDIsIm5iZiI6MTcyMTcxNjM0MiwicGF0aCI6Ii8xMzk5OTYzLzM1MDgyNTEzNi1lMDg5ZTk1Yy03NTg5LTQ3ZGMtODhmYS0wOTdmMWFhNzExYzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjNUMDYzMjIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDRmYmE5MTQzYTQyZGI5ODU0MzVjM2UxMTAwOTRmZGVmNjY2OGQzZTEwMjNiNThmYjQ2YTcxYTI4YWZjNTgwYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LqwXSai2DuGzZwnFZHatfGIdqgSnM4Y2_4w6HDGngv8) 显示位置还有问题, 以下是实现代码，帮忙看看
> 
> ```ts
>           /* 文字纵向显示(旋转270度) */
>           while (this.getValue(text.width()) > this.getValue(cellSize) * 4.6) {
>             fontSize -= 1
>             text.fontSize(this.getValue(fontSize))
>           }
>           text.setAttrs({
>             rotation: 270,
>             x: text.height() / 2,
>             offsetX: text.width() / 2,
>             offsetY: text.height() / 2,
>           });
> ```

第一，问题是什么？
第二，自行调整 y 的距离就行，文字宽度 通过 text.width 可以得到，上移一半的宽度应该可以吧

**Comment by programlife555** [comment]
x 的位置怎样计算出来? 刚好在刻度挨着刻度线

**Comment by xachary** [comment]
> x 的位置怎样计算出来? 刚好在刻度挨着刻度线

根据行高和比例尺大小计算合适的x
